# Dockerfile for Celery worker

# Use the same Python runtime as the Django application
FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . /code/

# Run the Celery worker
CMD ["celery", "-A", "netology_pd_diplom", "worker", "-l", "info"]