# Dockerfile for Celery worker

# Use the same Python runtime as the Django application
FROM python:3.12

COPY ./ /netology_pd_diplom

# Set work directory
WORKDIR . /netology_pd_diplom

# Install dependencies
COPY requirements.txt . /netology_pd_diplom/
RUN pip install --no-cache-dir -r requirements.txt

# Run the Celery worker
CMD ["celery", "-A", "netology_pd_diplom", "worker", "-l", "info"]